env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  no-console: off
  no-unused-vars: warn
  prettier/prettier:
    -
      error
    -
      singleQuote: true
      trailingComma: es5
